version: "3"
services:
  frontend:
    image: taieb98/todo_react_img
    ports:
      - ${{secrets.FRONT_ACCESS_PORT}}:${{secrets.FRONT_ACCESS_PORT}}
    stdin_open: true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    container_name: frontend
    restart: always 
  backend:
    container_name: backend
    restart: always
    image: taieb98/backend_img
    ports:
      - ${{secrets.BACKEND_ACCESS_PORT}}:${{secrets.BACKEND_ACCESS_PORT}}
    volumes:
      - ./backend:/app
      - /app/node_modules
    
 