name: back CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]  
  workflow_dispatch:

jobs:
  back_ci:
    runs-on: ubuntu-latest
    steps:
    - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile